### ISSUE TITLE
Getting compilation error with version 3.7.0: UglifyJs fails

### ISSUE THREAD

**Issue by CryptoMeerkat** [michaelwittig/node-i18n-iso-countries#99] opened 2018-06-27 07:27 UTC
Hi there,

we are using i18n-iso-countries with webpack. Maybe someone else stumbles upon this and receives the following:
```
2018-06-26T14:50:41.5178144Z WARNING in ./node_modules/i18n-iso-countries/index.js
2018-06-26T14:50:41.5178337Z 46:18-63 Critical dependency: the request of a dependency is an expression
2018-06-26T14:50:41.5178523Z  @ ./node_modules/i18n-iso-countries/index.js
2018-06-26T14:50:41.5178679Z  @ ./src/i18n/i18nCountries.js
2018-06-26T14:50:41.5178825Z  @ ./src/index.jsx
2018-06-26T14:50:41.5178965Z  @ multi ./src/index.jsx
2018-06-26T14:50:41.5179055Z 
2018-06-26T14:50:41.5179351Z ERROR in bundle.js from UglifyJs
2018-06-26T14:50:41.5179512Z Unexpected token: name (localData) [bundle.js:29002,6]
```

We had now one day broken builds because of that. The reason was, that in our `package.json` we allowed also minor version upgrades with `"i18n-iso-countries": "^3.6.2"`. Changing it to "i18n-iso-countries": "~3.6.2" to ensure only patching is done and it stays at version 3.6.x solved it.

I actually even commented out the minification with UglifyJs, but yet the error still persists. I guess it has to do with missing ES6 transpilation or something like that in i18n-iso-countries and thus UglifyJs fails. However, I do not want to include the `node_modules` folder in my ES6 transpilation process.

**Comment by michaelwittig** [comment] 2018-06-27 11:29
duplicate of #98

**Closed by michaelwittig** 2018-06-27 11:29 UTC
