### ISSUE TITLE
Impossible to use this module with create-react-app

### ISSUE THREAD

**Issue by Gpx** [michaelwittig/node-i18n-iso-countries#108] opened 2018-07-05 15:08 UTC
I'm trying to use this module with create-react-app but I get a compilation error:

```
Failed to minify the code from this file: 

 	./node_modules/i18n-iso-countries/index.js:46 

Read more here: http://bit.ly/2tRViJ9
```

Following the link brings to this page: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

> Open an issue on the dependency's issue tracker and ask that the package be published pre-compiled.

Any chance the module could be pre-compiled before it's published?

**Comment by michaelwittig** [comment] 2018-07-05 18:04
Duplicate of #98 
Please use `i18n-iso-countries@3.7.3`

**Closed by michaelwittig** 2018-07-05 18:04 UTC
