### ISSUE TITLE
New Request

### ISSUE THREAD

**Issue by Jalil-Irfan** [michaelwittig/node-i18n-iso-countries#315] opened 2022-12-08 10:05 UTC
Can you also add in ISD calling code for each country  like +1, +203, +91 , and if possible the mobile number format like (+91) 94321 87693, (+1) 808-808-8008,

**Comment by michaelwittig** [comment] 2022-12-08 13:03
duplicate of #300

**Closed by michaelwittig** 2022-12-08 13:03 UTC
